# Generated by Django 5.2.1 on 2025-05-16 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "proficiency",
                    models.IntegerField(help_text="Proficiency level from 1-100"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("programming", "Programming Languages"),
                            ("framework", "Frameworks"),
                            ("database", "Databases"),
                            ("tool", "Tools & Technologies"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="projects/")),
                ("github_link", models.URLField(blank=True)),
                ("live_link", models.URLField(blank=True)),
                ("date_completed", models.DateField()),
                ("technologies", models.ManyToManyField(to="portfolio.skill")),
            ],
        ),
    ]
